name: critterpedia
description: A tool to track fish and bugs in ACNH
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  json_annotation: ^3.0.1
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
flutter:
  uses-material-design: true
